name: Automate LeetHub Updates

on:
  push:
    branches:
      - main

jobs:
  automate-leethub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Create or update leethub-updates branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        # Check if the leethub-updates branch exists
        if git show-ref --quiet refs/heads/leethub-updates; then
          git checkout leethub-updates
          git pull origin leethub-updates
        else
          git checkout -b leethub-updates
        fi

    - name: Merge changes from main to leethub-updates
      run: |
        git merge main

    - name: Push changes to leethub-updates
      run: |
        git push origin leethub-updates
